version: "3.8"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - ./frontend/node_modules:/app/node_modules
            - ./frontend/.next:/app/.next
        environment:
            - NODE_ENV=development
        command: npm run dev
        depends_on:
            - backend
        networks:
            default:
    backend:
        build: ./backend
        ports:
          - "8000:8000"
        volumes:
         - ./backend:/app
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        networks:
            default:
    db:
        image: postgres:16-alpine
        ports:
           - "5432:5432"
        environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: postgres
           POSTGRES_HOST_AUTH_METHOD: md5
           POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
           PGDATA: /var/lib/postgresql/data/pgdata
        command: >
            postgres 
            -c listen_addresses='*' 
            -c max_connections=100
            -c log_connections=on
            -c log_destination='stderr'
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        networks:
            default:
networks:
    default:
volumes:
    pgdata: